# Form implementation generated from reading ui file 'UI_SettingWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName("SettingWindow")
        SettingWindow.resize(283, 184)
        SettingWindow.setAutoFillBackground(False)
        self.collect = QtWidgets.QLabel(parent=SettingWindow)
        self.collect.setGeometry(QtCore.QRect(30, 70, 31, 20))
        self.collect.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.collect.setObjectName("collect")
        self.sale = QtWidgets.QLabel(parent=SettingWindow)
        self.sale.setGeometry(QtCore.QRect(30, 90, 31, 20))
        self.sale.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.sale.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.sale.setObjectName("sale")
        self.label = QtWidgets.QLabel(parent=SettingWindow)
        self.label.setGeometry(QtCore.QRect(70, 0, 161, 61))
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.collect_toolButton = QtWidgets.QToolButton(parent=SettingWindow)
        self.collect_toolButton.setGeometry(QtCore.QRect(70, 70, 24, 21))
        self.collect_toolButton.setAutoFillBackground(True)
        self.collect_toolButton.setObjectName("collect_toolButton")
        self.pull_toolButton = QtWidgets.QToolButton(parent=SettingWindow)
        self.pull_toolButton.setGeometry(QtCore.QRect(70, 90, 24, 21))
        self.pull_toolButton.setObjectName("pull_toolButton")
        self.pull = QtWidgets.QLabel(parent=SettingWindow)
        self.pull.setGeometry(QtCore.QRect(30, 110, 31, 20))
        self.pull.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.pull.setObjectName("pull")
        self.sale_toolButton = QtWidgets.QToolButton(parent=SettingWindow)
        self.sale_toolButton.setGeometry(QtCore.QRect(70, 110, 24, 21))
        self.sale_toolButton.setObjectName("sale_toolButton")
        self.bg_title = QtWidgets.QLabel(parent=SettingWindow)
        self.bg_title.setGeometry(QtCore.QRect(120, 90, 71, 20))
        self.bg_title.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.bg_title.setObjectName("bg_title")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=SettingWindow)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 90, 95, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=SettingWindow)
        self.radioButton_3.setGeometry(QtCore.QRect(190, 120, 95, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=SettingWindow)
        self.radioButton_4.setGeometry(QtCore.QRect(190, 60, 95, 19))
        self.radioButton_4.setObjectName("radioButton_4")

        self.retranslateUi(SettingWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingWindow.setWindowTitle(_translate("SettingWindow", "设置"))
        self.collect.setText(_translate("SettingWindow", "<html><head/><body><p><span style=\" color:#acc8e6;\">收藏：</span></p></body></html>"))
        self.sale.setText(_translate("SettingWindow", "<html><head/><body><p><span style=\" color:#9bc3e6;\">出售：</span></p></body></html>"))
        self.label.setText(_translate("SettingWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">请按游戏中规则绑定对应按键</span></p></body></html>"))
        self.collect_toolButton.setText(_translate("SettingWindow", "f1"))
        self.pull_toolButton.setText(_translate("SettingWindow", "f1"))
        self.pull.setText(_translate("SettingWindow", "<html><head/><body><p><span style=\" color:#acc8e6;\">抛竿：</span></p></body></html>"))
        self.sale_toolButton.setText(_translate("SettingWindow", "f1"))
        self.bg_title.setText(_translate("SettingWindow", "<html><head/><body><p><span style=\" color:#acc8e6;\">主窗口背景：</span></p></body></html>"))
        self.radioButton_2.setText(_translate("SettingWindow", "背景2"))
        self.radioButton_3.setText(_translate("SettingWindow", "背景3"))
        self.radioButton_4.setText(_translate("SettingWindow", "背景1"))
